#!/bin/bash
#reconfigure squid and dropbear

# initializing variable
OS=`uname -m`;
MYIP=$(curl -4 icanhazip.com)
if [ $MYIP = "" ]; then
   MYIP=`ifconfig | grep 'inet addr:' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d: -f2 | awk '{ print $1}' | head -1`;
fi
MYIP2="s/xxxxxxxxx/$MYIP/g";
sleep 1

#prevent losing sshd port
cd
sudo echo "NO_START=0
DROPBEAR_PORT="9933"

DROPBEAR_EXTRA_ARGS=""-p 2110 ""
DROPBEAR_BANNER="/etc/issue.net"
DROPBEAR_RECEIVE_WINDOW=65536" > /etc/default/dropbear
sleep 1



#optimize squid config
cd
sudo echo "cache_mem 200 MB
maximum_object_size_in_memory 32 KB
maximum_object_size 1024 MB
minimum_object_size 0 KB
cache_swap_low 90
cache_swap_high 95
cache_dir ufs /var/spool/squid3 100 16 256
access_log /var/log/squid3/access.log squid
acl localhost src 127.0.0.1/32 ::1
acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777
acl CONNECT method CONNECT
acl SSH dst $MYIP-$MYIP/32
http_access allow SSH
http_access allow manager localhost
http_access deny manager
http_access allow localhost
http_access deny all
http_port 61790
http_port 8000
http_port 3993
relaxed_header_parser off
coredump_dir /var/spool/squid3
refresh_pattern ^ftp: 1440 20% 10080
refresh_pattern ^gopher: 1440 0% 1440
refresh_pattern -i (/cgi-bin/|\?) 0 0% 0
refresh_pattern . 0 20% 4320
visible_hostname Gwapong Lander" > /etc/squid/squid.conf


cd
sudo echo "Port 333" >> /etc/ssh/sshd_config
sudo echo "Port 334" >> /etc/ssh/sshd_config
sudo echo "Port 335" >> /etc/ssh/sshd_config
sudo echo "Banner /etc/issue.net" >> /etc/ssh/sshd_config

