#!/bin/bash
source cabecalho
#[[ -e /etc/bash.bashrc-bakup ]] && _autorun="\033[1;32m${txt[10]}" || _autorun="\033[1;31m${txt[11]}"

echo""
echo -e "-----=[ Account Management Section ]=-----" | lolcat
echo -e "${cor[2]} [0] > Exit Menu" 
echo -e "${cor[2]} [1] > Create Account"  | lolcat
echo -e "${cor[2]} [2] > Delete Account" | lolcat
echo -e "${cor[2]} [3] > Account Editor" | lolcat
echo -e "${cor[2]} [4] > Account List and Details" | lolcat
echo -e "${cor[2]} [5] > Online Users" | lolcat
echo -e "${cor[2]} [6] > Create All Accounts Backup" | lolcat
echo -e "${cor[2]} [7] > Restore Backup" | lolcat

echo ""
echo -e "-----=[ Security and Tweaks Section ]=-----" | lolcat
echo -e "${cor[2]} [8]  > Brute Force Payload Simulation" | lolcat
echo -e "${cor[2]} [9]  >  Torrent and Port Protection" | lolcat
echo -e "${cor[2]} [10] > Installation Log" | lolcat
echo -e "${cor[2]} [11] > Shadow Socks $shadow" | lolcat
echo -e "${cor[2]} [12] > Python Proxy $socks" | lolcat
echo -e "${cor[2]} [13] > Telegram Manager Bot $telegran" | lolcat
echo ""





