#!/bin/bash
source cabecalho
#[[ -e /etc/bash.bashrc-bakup ]] && _autorun="\033[1;32m${txt[10]}" || _autorun="\033[1;31m${txt[11]}"

echo""
echo -e "-----=[ Account Management Section ]=-----" 
echo -e "${cor[2]} [0] > Exit Menu" 
echo -e "${cor[2]} [1] > Create User Account" 
echo -e "${cor[2]} [2] > Delete User Account" 
echo -e "${cor[2]} [3] > User Account Editor"
echo -e "${cor[2]} [4] > User Account List and Details"
echo -e "${cor[2]} [5] > Online Users" 
echo -e "${cor[2]} [6] > Create All User Accounts Backup" 
echo -e "${cor[2]} [7] > Restore Backup" 

echo ""
echo -e "-----=[ Server Management Section ]=-----"
echo -e "${cor[2]} [8]  > Brute Force Payload Simulation" 
echo -e "${cor[2]} [9]  > Telegram Manager Bot $telegran"
echo -e "${cor[2]} [10] > Openvpn $openvpn"
echo -e "${cor[2]} [11] > SSL Tunnel $stunel" 
echo -e "${cor[2]} [12] > Shadow Socks $shadow" 
echo -e "${cor[2]} [13] > Python Proxy $socks"
echo -e "${cor[2]} [14] > Installation Log"


