#!/bin/bash
source menu-txt
echo -ne "${cor[6]}"
read -p " ${txt[9]} " _selecao
case $_selecao in
0)
clear
echo -e "${cor[0]}"
exit
;;
1)
clear
source user
exit
;;
2)
clear
source ferramentas
exit
;;
3)
$value > /dev/null 2>&1
chmod +x /etc/adm-lite/*
[[ -e /etc/adm-lite/idioma_menuinst ]] && idioma=$(cat /etc/adm-lite/idioma_menuinst|head -1) || idioma="pt"
value=$(vary_rex "2f6574632f61646d2d6c6974652f6d656e755f696e7374")
${value} ${idioma}
exit
;;
4)
sudo auto-reboot
exit
;;
5)
sudo user-login
exit
;;

*)
source menu
;;
esac
