#!/bin/bash
source cabecalho
#[[ -e /etc/bash.bashrc-bakup ]] && _autorun="\033[1;32m${txt[10]}" || _autorun="\033[1;31m${txt[11]}"

echo""
echo -e "-----=[ Account Management Section ]=-----" | lolcat
echo -e "${cor[2]} [1] > Create Account"  | lolcat
echo -e "${cor[2]} [2] > Delete Account" | lolcat
echo -e "${cor[2]} [3] > Account Editor" | lolcat
echo -e "${cor[2]} [4] > Account List and Details" | lolcat
echo -e "${cor[2]} [5] > Online Users" | lolcat
echo -e "${cor[2]} [6] > Delete Expired Account" | lolcat
echo -e "${cor[2]} [7] > Create All Accounts Backup" | lolcat
echo -e "${cor[2]} [8] > Restore Backup" | lolcat

echo ""
echo -e "-----=[ Security and Tweaks Section ]=-----" | lolcat
echo -e "${cor[2]} [9]   > Clear Cache" | lolcat
echo -e "${cor[2]} [10] > BADVPN $_badvpn" | lolcat
echo -e "${cor[2]} [11] > TCP Speed Up $_tcpspeed" | lolcat
echo -e "${cor[2]} [12] > Fail2Ban $fail_b" | lolcat
echo -e "${cor[2]} [13] > Brute Force Payload Simulation" | lolcat
echo -e "${cor[2]} [14] > Anti Torrent" | lolcat
echo -e "${cor[2]} [15] > DDoS $ddos" | lolcat
echo -e "${cor[2]} [16] > Speed Up Patch" | lolcat
echo -e "${cor[2]} [17] > Auto Reboot Scheduler" | lolcat

echo ""
echo -e "-----=[ Essential Installer Section ]=-----" | lolcat
echo -e "${cor[2]} [18] > Squid Proxy $squid" | lolcat
echo -e "${cor[2]} [19] > Dropbear $dropbear" | lolcat
echo -e "${cor[2]} [20] > Openvpn $openvpn" | lolcat
echo -e "${cor[2]} [21] > SSL Tunnel $stunel" | lolcat
echo -e "${cor[2]} [22] > Shadow Socks $shadow" | lolcat
echo -e "${cor[2]} [23] > Python Proxy $socks" | lolcat
echo -e "${cor[2]} [24] > Telegram Manager Bot $telegran" | lolcat
echo -e "${cor[2]} [25] > Webmin $webminn" | lolcat
echo -e "${cor[2]} [26] > Exit Menu" | lolcat





